### ISSUE TITLE
The seq.output of test differ depending on input.

### ISSUE THREAD

**Issue by byeonggill** [xunchen85/VIcaller#1]
[ss.xlsx](https://github.com/xunchen85/VIcaller/files/3056970/ss.xlsx)

This xlsx file consist of three seq.output.
Row 2 is your's seq.output.
Row 3 is output received seq_WGS.bam file as input
Row 4 is output received seq_1.fastq.gz and seq_2.fastq.gz file as input.
Why are the three output different?

my cmd: perl VIcaller.pl detect -d WGS -i test/seq_WGS -f .bam -s paired-end
my config
export PERL5LIB=/etc/perl:/usr/local/lib/x86_64-linux-gnu/perl/5.22.1:/usr/local/share/perl/5.22.1:/usr/lib/x86_64-linux-gnu/perl5/5.22:/usr/share/perl5:/usr/lib/x86_64-linux-gnu/perl/5.22:/usr/share/perl/5.22:/usr/local/lib/site_perl:/usr/lib/x86_64-linux-gnu/perl-base
export PATH=$PATH:/data/program/bowtie2/bowtie2-2.2.9/
 human_genome = /data/program/VIcaller_v1.1/Database/Human/hg38.fa
 human_genome_tophat = /data/program/VIcaller_v1.1/Database/Human/hg38.fa
 virus_genome = /data/program/VIcaller_v1.1/Database/Virus/virus_db_090217.fa
 virus_taxonomy = /data/program/VIcaller_v1.1/Database/Virus/virus_db_090217.taxonomy
 virus_list = /data/program/VIcaller_v1.1/Database/Virus/virus_db_090217.virus_list
 vector_db = /gpfs2/dli5lab/CAVirus/Database/Vector/Vector.fa
 cell_line = /data/program/VIcaller_v1.1/Database/cell_line.list
\# bowtie_d = /data/program/bowtie2/bowtie2-2.2.9/
\# tophat_d = /data/program/tophat/tophat-2.1.0.Linux_x86_64/
\# bwa_d = /data/program/bwa/bwa/
\# samtools_d = /data/program/samtools/samtools-1.9/
\# repeatmasker_d = /data/program/RepeatMasker/
\# meme_d = /data/program/meme/
\# NGSQCToolkit_d = /data/program/NGS_QC_Toolkit/
\# fastuniq_d = /data/program/FastUniq/
\# SE_MEI_d = /data/program/VIcaller_v1.1/Tools/SE-MEI/
\# hydra_d = /data/program/Hydra-Version-0.5.3/
\# blat_d = /home/hikim/bin/x86_64/
\# blastn_d = /data/program/blast/ncbi-blast-2.5.0+

**Comment by xunchen85** [comment]
It is mainly because of the different human reference genome builds. 

The test output file (Row 2 in the excel) and the input file in BAM format (test_WGS.bam) (Row 3 in the excel) are based on the hg19 reference sequence. 

Hopefully it is helpful.

**Comment by byeonggill** [comment]
thanks you for answer.

I have another question about running tools.
I think maybe VIcaller.pl line 396 do not run my system.
but, this code run normally, if typing the command manually.

This is Vicaller.pl code.
![image](https://user-images.githubusercontent.com/49423291/55859962-21bd4500-5bae-11e9-8f80-1877db7aebb9.png)

This is my log files. 
![image](https://user-images.githubusercontent.com/49423291/55860384-0f8fd680-5baf-11e9-828a-73c419c3c86b.png)
Line 472: fail to locate the index files.
but I have Vector.fa and  bwa indexing file.

This is my config
![image](https://user-images.githubusercontent.com/49423291/55860805-fcc9d180-5baf-11e9-9e50-588a7ce18f3f.png)

This is Vector.fa
![image](https://user-images.githubusercontent.com/49423291/55860840-0f440b00-5bb0-11e9-8680-5851014c9536.png)

**Comment by byeonggill** [comment]
thanks for answer!

**Comment by xunchen85** [comment]
It results in the mistake of your config file specifying $vector_db.

There should be a space between # and vector_db.

Xun

**Comment by byeonggill** [comment]
I've just seen the answer.
I revised my config($vector_db)
It was my mistake.

but I have another problems.

please see the #2 

thanks you!
