### ISSUE TITLE
What is input file of calculate?

### ISSUE THREAD

**Issue by byeonggill** [xunchen85/VIcaller#3]
calculate parameter
![image](https://user-images.githubusercontent.com/49423291/56127171-82d28780-5fb7-11e9-881f-9e7628cf9e5b.png)

What is input file of calculate?
I don't know what to do with parameter -F
inputID_h.bam?
inputID_h1.sort.bam?
 
and, 
Is the parameter -N the column No._reads_supporting_VI?

**Comment by xunchen85** [comment]
The input is actually the same as the detect function "-f", which can be fastq or bam format. it is unclear before, i have revise the script to directly use "inputID_h.bam" if the original input file is fastq format.

It is correct that -N is the column No._reads_supporting_VI.
