### ISSUE TITLE
How to filter the list from the "detect" result

### ISSUE THREAD

**Issue by xflicsu** [xunchen85/VIcaller#5]
Hi Dr. Xun,
I got several candidate virus in my RNA-Seq data sets by the "detect" function of VIcaller.
I read the user manual of VIcaller.
It provide "validate" and "calculate" function of VIcaller to select only one interested virus.
Du to "detect" function detected numerous viruses,  how to select those viruses only in one step?

**Comment by xunchen85** [comment]
It is suggested to include the parameter of “-r”, which can remove most of the candidates. 

The “validate” function can be used to validate each detected viral integration per command line, however you can put each command lines in a shell script to run all of the kept candidates.    

Best,
Xun

**Comment by xflicsu** [comment]
Thanks for your response!
I am also interested in the "-a" parameter. 
How this parameter works, and would I consider add this parameter in "detection" process?

**Comment by xunchen85** [comment]
Yes, if you correctly installed VIcaller, you can simply include it as a parameter of "detect" function. 

Cheers,
Xun
