### ISSUE TITLE
About input data

### ISSUE THREAD

**Issue by oghzzang** [xunchen85/VIcaller#7]
Dear VIcaller team, 

Hi, I'm Oh. 

I have a question. 

Can I use alignment file derived from paired-end WGS data? 
ex) perl VIcaller.pl detect -d WGS -I sample -f .bam -s paired-end

There is no method using alignment file of WGS in user manual. 

Thanks. 

Oh.

**Comment by xunchen85** [comment]
Hi Oh,

Yes you can. We showed some examples with various combinations of parameters. you can use single-end/paired-end WGS, RNA-seq data as the input.

Best,
Xun
