### ISSUE TITLE
Tophat with --no-coverage-search

### ISSUE THREAD

**Issue by stsergbg** [xunchen85/VIcaller#8]
Hi!

When running VIcaller on one stage tophat suggests running itself in --no-coverage-search mode to make the process much faster. The run indeed completes much faster when this option is added to VIcaller.pl, so I wanted to ask if you tested this option before. Does this option (or can it, in principle), in your opinion, prevent VIcaller from finding/validating some viral integrations?

Sergei

**Comment by xunchen85** [comment]
Thanks for your question.

I haven't tried it yet! But in principle, it won't matter regarding finding or validating viral integrations. If it really speeds it up, I may also update to use --no-coverage-search mode in our tool.

Xun

**Comment by stsergbg** [comment]
Yes, for a couple of samples I've tested there is a significant improvement in speed. I also wanted to ask if tophat is crucial or other aligners might be just as good for the first alignment, e.g. STAR? As I've understood from the code tophat is run on default parameters and the main workhorse in the tool is bwa. 

By the way, when there is bam provided to the tool instead of fastq, as I got it, it is then converted to fastq only to be aligned afterwards with tophat again. Can this step be skipped altogether if I have a STAR-aligned bam file (to the same human reference) right from the start?

**Comment by xunchen85** [comment]
Tophat is only used for detect viral fusion transcript from RNA-seq data. 

You are correct, if the aligner can generate the BAM file with CIGAR column, VIcaller should be able to take the output BAM file as the input.

If the input is BAM file, it will convert the discordant reads into FASTQ and then re-align those reads using BWA. Tophat is only used for aligning FASTQ against human reference if the input is FASTQ format. In another word, if you provided a STAR-aligned BAM file, VIcaller should not re-run Tophat against the human reference.

Let me know if you found issues with it.

Best,

**Comment by stsergbg** [comment]
Thank you for the explanation! I've misunderstood the procedure with bam files as input, and now I tried running the tool on the already computed STAR bams - it works like a charm.
